apply from: "$rootDir/gradle/PromotionSupport.gradle"

task promoteToPublic(type: PromotionTask) {

    javaSrc = "EPM-RTC-java"
    javaDst = "EPM-RTC-public-java"
    
    doLast {
        printPromotionSettings()

        // Java
        promoteJava('deltix.qsrv:deltix-commons-collections')
        promoteJava('deltix.qsrv:deltix-commons-gui')
        promoteJava('deltix.qsrv:deltix-commons-lang')
        //promoteJava('deltix.qsrv:deltix-commons-log') // Deprecated
        promoteJava('deltix.qsrv:deltix-commons-tools')
        promoteJava('deltix.qsrv:deltix-commons-util')
        
    }
}
