title.query            	QuantView - Version %s

title.confirmation      Confirmation
title.information      	Information
title.error      		Error
title.compilationError  Compilation Error
title.exprTypeMismatch  Expressions Types Mismatch
title.entitypattern	   	Symbol
title.entities          Symbols
title.entities50        Symbols (first 50)
title.connections      	Connections

title.connectiondlg     Connection Parameters
label.host              Host:
label.port              Port:

shouldExit              Exit?

file              		File
new              		New
open              		Open
save              		Save
exit              		Exit

label.taxonomy          Taxonomy:
label.from              From:
label.to                To:
label.entities          Symbols:
label.key               Key:
label.name              Name:
label.description       Description:
label.documentation     Documentation:
label.datatype          Data type:
label.adjusted          Adjusted:
label.unadjusted        Unadjusted:

label.updatefrequencies Frequency
label.currencies        Currencies
label.adjustments       Split adjustments
label.domaingroup       Domain attribute group

label.datasourceid      Data Source ID:
label.providertype      Provider type:
label.entityfilter      Symbol Filter:
label.memorycompression Memory Compression:
label.rebuildprogress   Rebuild Progress:
label.cachestatus       Cache Status:
label.ismodified        Is Modified:
label.persistentconfigurations       Persistent Configurations:
label.pathfromdomain    Path From Domain:
label.formula           Formula:
label.referencepath     Reference Path:
label.size              Size:
label.path              Path:

label.cache             Cache:

label.varysqlinfo       Definition:
label.table             Table
label.columnName        Column Name
label.keyColumn         Key Column
label.dateColumn        Date Column
label.selected          Selected

lbl.applyTransformation	Apply Transformation:
lbl.useCaseInsensitive	Use Case Insensitive:
lbl.pattern	   			Pattern:
lbl.replacement	   		Replacement:
lbl.preview	   			Preview:

lbl.server				Host:
lbl.port				Port:
lbl.user			    User:
lbl.password			Password:

btn.edit                Edit
btn.query               Query
btn.expandeall          Expand All
btn.collapseall         Collapse All
lbl.selecttaxonomy      Select Taxonomy:

header.entityKey        Symbol
header.time             Time
header.seq              #

msg.connectionmustbesel	Active connection must be selected.
msg.serverIsUnavailable	Server '%s' on the port %s is unavailable
msg.autherror       	Authentication error: %s
msg.connectionsucceeded	Connection succeeded.
btn.testconnection		Test Connection...
check.enablessl         Enable SSL
check.useauth           Secure Authentication

dialog.tbauth.btn.ro    Read-Only
dialog.tbauth.btn.rw    Read-Write
dialog.tbauth.btn.max   Maximum allowed privileges
dialog.tbauth.btn.close Cancel


tab.history             History
tab.entities            Symbols

exprTypeMismatch        Expression evaluates to %0s instead of required %1s.
emptyExpr               Expression is required

action.newConnection    New
action.newConnection.tt Create Connection
action.remConnection    Remove
action.remConnection.tt Remove Connection

tree.tooltip.format     <html><b>Path:</b>&nbsp;%s<br><b>Description:</b><br>%s</html>

