
dependencies {
    implementation project(':lang'),
                   project(':collections'),
                   project(':util')

    // company repository
    api 'com.jidesoft:deltix-jide-components',
        'com.jidesoft:deltix-jide-dialogs',
        'com.jidesoft:deltix-jide-action',
        'com.jidesoft:deltix-jide-dock'

    api ('com.jidesoft:deltix-jide-grids') {
        exclude module: 'log4j'
        exclude module: 'commons-logging'
    }

    implementation('org.swinglabs:swingx:1.6') // have filters.jar v:2.0.235 in dependencies
    implementation('com.jgoodies:jgoodies-forms:1.6.0')            // have jgoodies-common.jar v:1.4.0 in dependencies
    implementation('com.jgoodies:jgoodies-looks:2.5.2')
    implementation('com.jgoodies:jgoodies-binding:2.7.0'){ transitive = false }
    implementation('com.jgoodies:jgoodies-validation:2.4.2'){ transitive = false }
    implementation('org.swinglabs:jxlayer:3.0.4'){ transitive = false }
}
