// Developers: please put credentials into ~/.gradle/gradle.properties
// CI Build robots get these credentials from CI Environment Variables
def repoUser = findProperty('NEXUS_USER') ?: System.getenv('NEXUS_USER') ?: "FakeNexusUser"
def repoPassword = findProperty('NEXUS_PASS') ?: System.getenv('NEXUS_PASS') ?: "FakeNexusPass"
def proxyRepository = findProperty('DELTIX_PROXY_REPOSITORY') ?: System.getenv('DELTIX_PROXY_REPOSITORY') ?: "https://nexus.deltixhub.com/repository/"

gradle.beforeProject {
    if (repoUser == null)
        ant.fail('ERROR: Credentials to access nexus.deltixhub.com repo are NOT defined!\nSee https://gitlab.deltixhub.com/Deltix/Common/MultilingualPackage/wikis/ProGetCredentials')
}

// need this for plugin repos in collections\build.gradle
rootProject.ext.repoUser = repoUser
rootProject.ext.repoPassword = repoPassword
rootProject.ext.proxyRepository = proxyRepository

repositories.ext.mavenDeltixProxy = { name ->
    repositories.maven {
        credentials {
            username = repoUser
            password = repoPassword
        }
        authentication {
            digest(BasicAuthentication)
        }
        url = proxyRepository + name + "/"
    }
}

