dependencies {
    compile project(':commons:lang')
    compile project(':commons:collections')
    compile('commons-lang:commons-lang:2.4') { transitive = false }

    //TODO: Since we no longer use IKVM we can switch to Java's version of JAXB
    compile files('../../../lib/endorsed/jaxb-api.jar'),
            files('../../../lib/jaxb/activation.jar'),
            files('../../../lib/jaxb/jaxb-impl.jar'),
            files('../../../lib/jaxb/jaxb-xjc.jar'),
            files('../../../lib/jaxb/jsr173_1.0_api.jar')

}

jar {
    manifest {
        baseName 'deltix-commons-util'
        attributes 'Implementation-Title': 'Deltix Commons Util',
                   'Implementation-Version': version
    }
}
