description = 'QuantServer general purpose utilities'

dependencies {
    compile project(':java:commons:lang'),
            project(':java:commons:collections'),
            project(':java:commons:messages')
    compile 'commons-lang:commons-lang:2.4',
            'org.apache.commons:commons-compress:1.7',
            'javax.servlet:javax.servlet-api:3.1.0'

    //TODO: Since we no longer use IKVM we can switch to Java's version of JAXB
//    compile files('../../../lib/endorsed/jaxb-api.jar'),
//            files('../../../lib/jaxb/activation.jar'),
//            files('../../../lib/jaxb/jaxb-impl.jar'),
//            files('../../../lib/jaxb/jaxb-xjc.jar'),
//            files('../../../lib/jaxb/jsr173_1.0_api.jar')
    compile('com.sun.xml.bind:jaxb-xjc:2.1.6')          // have jaxb-impl.jar v:2.1.6 & activation.jar v:1.1 & jaxb-api.jar v:2.1 in dependencies
    compile('javax.xml:jsr173:1.0'){ transitive = false }


//            files('../../../lib/jna.jar'),
//            files('../../../lib/platform.jar'),
//            files('../../../lib/bcel-6.0-SNAPSHOT.jar')
    compile('net.java.dev.jna:jna:3.4.0'){ transitive = false }
    compile('net.java.dev.jna:platform:3.4.0'){ transitive = false }
    compile('org.apache.bcel:bcel:6.0'){ transitive = false }

    testCompile project(':java:commons:lang').sourceSets.test.output
}
