//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace EPAM.Deltix.Timebase.Messages
{
    
    
    /// <summary>
    /// Defines a field as bitmask.
    /// </summary>
    [AttributeUsage(System.AttributeTargets.Enum, AllowMultiple=false)]
    public class BitmaskAttribute : System.Attribute
    {
        
        public BitmaskAttribute()
        {
        }
    }
}
