//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using com.epam.deltix.containers.;
using System;


namespace EPAM.Deltix.Timebase.Messages
{
    
    
    /// <summary>
    /// Defines a field as encoded relative to another field.
    /// </summary>
    [AttributeUsage(((((System.AttributeTargets.Enum | System.AttributeTargets.Field) 
                | System.AttributeTargets.Interface) 
                | System.AttributeTargets.Property) 
                | System.AttributeTargets.Class), AllowMultiple=false)]
    public class RelativeToAttribute : System.Attribute
    {
        
        private String _value = null;
        
        public RelativeToAttribute()
        {
        }
        
        public RelativeToAttribute(String value)
        {
            this._value = value;
        }
        
        #region Properties
        public String Value
        {
            get
            {
                return this._value;
            }
            set
            {
                this._value = value;
            }
        }
        #endregion
    }
}
