//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using com.epam.deltix.containers.;
using System;


namespace EPAM.Deltix.Timebase.Messages
{
    
    
    /// <summary>
    /// Defines a static field.
    /// </summary>
    [AttributeUsage((System.AttributeTargets.Field | System.AttributeTargets.Property), AllowMultiple=false)]
    public class SchemaStaticTypeAttribute : System.Attribute
    {
        
        private String _value = null;
        
        private SchemaDataType _dataType = SchemaDataType.Default;
        
        public SchemaStaticTypeAttribute()
        {
        }
        
        #region Properties
        /// <summary>
        /// Defines a value for static field.
        /// </summary>
        public String Value
        {
            get
            {
                return this._value;
            }
            set
            {
                this._value = value;
            }
        }
        
        /// <summary>
        /// Defines schema data type of the field.
        /// If not defined, default mapping is used.
        /// </summary>
        public SchemaDataType DataType
        {
            get
            {
                return this._dataType;
            }
            set
            {
                this._dataType = value;
            }
        }
        #endregion
    }
}
