//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace EPAM.Deltix.Timebase.Messages
{
    
    
    /// <summary>
    /// Marks record field as hidden from UHF Serializer (excluded from channel transmission).
    /// Hidden fields are not available on the receiver (UHF Client) side.
    /// </summary>
    [AttributeUsage(((System.AttributeTargets.Field | System.AttributeTargets.Property) 
                | System.AttributeTargets.Class), AllowMultiple=false)]
    public class SchemaIgnoreAttribute : System.Attribute
    {
        
        public SchemaIgnoreAttribute()
        {
        }
    }
}
