/*
  Copyright 2021 EPAM Systems, Inc

  See the NOTICE file distributed with this work for additional information
  regarding copyright ownership. Licensed under the Apache License,
  Version 2.0 (the "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
  License for the specific language governing permissions and limitations under
  the License.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using com.epam.deltix.containers.;
using System;
using System.Collections.Generic;


namespace EPAM.Deltix.Timebase.Messages
{
    
    
    /// <summary>
    /// Defines a array field type in Timebase schema.
    /// </summary>
    [AttributeUsage((System.AttributeTargets.Field | System.AttributeTargets.Property), AllowMultiple=false)]
    public class SchemaArrayTypeAttribute : System.Attribute
    {
        
        private Boolean _isNullable = true;
        
        private Boolean _isElementNullable = true;
        
        private String _elementEncoding = null;
        
        private SchemaDataType _elementDataType = SchemaDataType.Default;
        
        private String _elementMinimum = null;
        
        private String _elementMaximum = null;
        
        private Type[] _elementTypes = new Type[0];
        
        public SchemaArrayTypeAttribute()
        {
        }
        
        #region Properties
        /// <summary>
        /// Defines if field allows null value to be assigned to it.
        /// </summary>
        public Boolean IsNullable
        {
            get
            {
                return this._isNullable;
            }
            set
            {
                this._isNullable = value;
            }
        }
        
        /// <summary>
        /// Defines if array element allows null values.
        /// </summary>
        public Boolean IsElementNullable
        {
            get
            {
                return this._isElementNullable;
            }
            set
            {
                this._isElementNullable = value;
            }
        }
        
        /// <summary>
        /// Defines Timebase encoding for the array element.
        /// </summary>
        public String ElementEncoding
        {
            get
            {
                return this._elementEncoding;
            }
            set
            {
                this._elementEncoding = value;
            }
        }
        
        /// <summary>
        /// Defines schema data type of the array element.
        /// If not defined, default mapping is used.
        /// </summary>
        public SchemaDataType ElementDataType
        {
            get
            {
                return this._elementDataType;
            }
            set
            {
                this._elementDataType = value;
            }
        }
        
        /// <summary>
        /// Defines minimum value of array element. (For numeric types only)
        /// </summary>
        public String ElementMinimum
        {
            get
            {
                return this._elementMinimum;
            }
            set
            {
                this._elementMinimum = value;
            }
        }
        
        /// <summary>
        /// Defines maximum value of array element. (For numeric types only)
        /// </summary>
        public String ElementMaximum
        {
            get
            {
                return this._elementMaximum;
            }
            set
            {
                this._elementMaximum = value;
            }
        }
        
        /// <summary>
        /// Defines a set of types that might reside in this field.
        /// </summary>
        public Type[] ElementTypes
        {
            get
            {
                return this._elementTypes;
            }
            set
            {
                this._elementTypes = value;
            }
        }
        #endregion
    }
}