//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using com.epam.deltix.containers.;
using System;


namespace EPAM.Deltix.Timebase.Messages
{
    
    
    /// <summary>
    /// Defines schema meta-information for the schema element.
    /// </summary>
    [AttributeUsage(((((System.AttributeTargets.Field | System.AttributeTargets.Property) 
                | System.AttributeTargets.Interface) 
                | System.AttributeTargets.Class) 
                | System.AttributeTargets.Enum), AllowMultiple=false)]
    public class SchemaElementAttribute : System.Attribute
    {
        
        private String _name = null;
        
        private String _title = null;
        
        private String _description = null;
        
        public SchemaElementAttribute()
        {
        }
        
        #region Properties
        /// <summary>
        /// Defines a user-visible name for a schema element.
        /// </summary>
        public String Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        /// <summary>
        /// Defines a user-visible title for a schema element.
        /// </summary>
        public String Title
        {
            get
            {
                return this._title;
            }
            set
            {
                this._title = value;
            }
        }
        
        /// <summary>
        /// Defines a user-visible description for a schema element.
        /// </summary>
        public String Description
        {
            get
            {
                return this._description;
            }
            set
            {
                this._description = value;
            }
        }
        #endregion
    }
}
