description = 'Timebase general purpose utilities'

configurations {
    antlrGenerator
}

dependencies {
    api project(':timebase-lang'),
        project(':timebase-collections')

    compileOnly 'org.jetbrains:annotations'

    implementation 'com.epam.deltix:thread-affinity'

    implementation 'org.apache.commons:commons-lang3'
    implementation 'org.apache.commons:commons-compress'

    api 'javax.xml.bind:jaxb-api:2.3.1'
    api 'com.sun.xml.bind:jaxb-impl:2.3.0'
    api 'com.sun.xml.bind:jaxb-core:2.3.0'

    implementation 'com.github.sarxos:windows-registry-util:0.3'
//    instead of 'org.green:green-jelly:0.1.0'
    implementation ("io.github.green4j:green-jelly:0.1.6")

    implementation('org.apache.bcel:bcel:6.6.0')

    implementation 'com.nimbusds:nimbus-jose-jwt:9.40'
    implementation 'org.bouncycastle:bcpkix-jdk18on:1.78.1'
    implementation 'com.github.scribejava:scribejava-apis:8.3.3'

    testImplementation 'org.junit.jupiter:junit-jupiter-params'

    implementation group: 'com.epam.deltix', name: 'hd-date-time', version: hdTimeVersion

    implementation group: 'org.antlr', name: 'antlr4-runtime', version: '4.6'
    antlrGenerator group: 'org.antlr', name: 'antlr4', version: '4.6'

    testImplementation 'com.epam.deltix:gflog-core'
    testImplementation 'com.epam.deltix:gflog-jul'
    testRuntimeOnly 'com.epam.deltix:gflog-slf4j'

//    testImplementation 'org.hdrhistogram:HdrHistogram'
    testImplementation 'org.mockito:mockito-core'

    // For simulation of connection loss scenarios
    testImplementation 'com.github.netcrusherorg:netcrusher-core:0.10'
}

// Synthetic Rule parser generator
def generatedAntlrDir = file('build/generated-src/antlr')
def grammarPath = "src/main/resources/antlr/SyntheticRule.g4"
def packageName = "com.epam.deltix.qsrv.hf.framework.mdp.impl.parser.generated"
def generatedPath = "$generatedAntlrDir/com/epam/deltix/qsrv/hf/framework/mdp/impl/parser/generated/"

tasks.register('generateSyntheticRuleGrammar', JavaExec) {
    group = "antlr"
    description = "Generates ANTLR files (Lexer, Parser, Visitor, etc.)"

    classpath = configurations.antlrGenerator
    mainClass = "org.antlr.v4.Tool"

    args = [
            grammarPath,
            "-package", packageName,
            "-o", generatedPath,
            "-no-listener",
            "-visitor"
    ]

    inputs.file(file(grammarPath))
            .withPropertyName("grammarFile")
            .withPathSensitivity(PathSensitivity.RELATIVE)

    outputs.dir(file(generatedPath))
            .withPropertyName("outputDir")
}

sourceSets.main.java.srcDirs generatedAntlrDir

tasks.compileJava {
    dependsOn generateSyntheticRuleGrammar
}
tasks.processResources {
    dependsOn generateSyntheticRuleGrammar
}