/*
  Copyright 2021 EPAM Systems, Inc

  See the NOTICE file distributed with this work for additional information
  regarding copyright ownership. Licensed under the Apache License,
  Version 2.0 (the "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
  License for the specific language governing permissions and limitations under
  the License.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EPAM.Deltix.Timebase.Messages;
using System;


namespace EPAM.Deltix.Timebase.Messages.Schema
{
    
    
    /// <summary>
    /// Schema definition of binary data type.
    /// </summary>
    [SchemaElement(Name="com.epam.deltix.timebase.messages.schema.BinaryDataType", Title="BinaryDataType", Description=null)]
    public class BinaryDataType : DataType, IBinaryDataTypeInterface
    {
        
        public new static string ClassName = "com.epam.deltix.timebase.messages.schema.BinaryDataType";
        
        private UInt32 _maxSize = UInt32.MinValue;
        
        private UInt16 _compressionLevel = UInt16.MinValue;
        
        /// <summary>
        /// Creates an instance of BinaryDataType object.
        /// </summary>
        public BinaryDataType()
        {
        }
        
        #region Properties
        /// <summary>
        /// Maximum field length in bytes.
        /// </summary>
        [SchemaElement(Name=null, Title=null, Description=null)]
        [SchemaType(Encoding=null, IsNullable=true, DataType=SchemaDataType.Default, Minimum=null, Maximum=null, NestedTypes=new Type[0])]
        public virtual UInt32 MaxSize
        {
            get
            {
                return this._maxSize;
            }
            set
            {
                this._maxSize = value;
            }
        }
        
        /// <summary>
        /// Compression level for binary data.
        /// </summary>
        [SchemaElement(Name=null, Title=null, Description=null)]
        [SchemaType(Encoding=null, IsNullable=true, DataType=SchemaDataType.Default, Minimum="0", Maximum="9", NestedTypes=new Type[0])]
        public virtual UInt16 CompressionLevel
        {
            get
            {
                return this._compressionLevel;
            }
            set
            {
                this._compressionLevel = value;
            }
        }
        #endregion
        
        #region Property Helpers
        /// <summary>
        /// Flag that indicates whether property MaxSize has an assigned value.
        /// <returns>true if property has an assigned value, false otherwise.</returns>
        /// </summary>
        public bool HasMaxSize()
        {
            return (this._maxSize != UInt32.MinValue);
        }
        
        /// <summary>
        /// Sets null to MaxSize property.
        /// </summary>
        public void NullifyMaxSize()
        {
            this._maxSize = UInt32.MinValue;
        }
        
        /// <summary>
        /// Flag that indicates whether property CompressionLevel has an assigned value.
        /// <returns>true if property has an assigned value, false otherwise.</returns>
        /// </summary>
        public bool HasCompressionLevel()
        {
            return (this._compressionLevel != UInt16.MinValue);
        }
        
        /// <summary>
        /// Sets null to CompressionLevel property.
        /// </summary>
        public void NullifyCompressionLevel()
        {
            this._compressionLevel = UInt16.MinValue;
        }
        #endregion
        
        #region Message Methods
        /// <summary>
        /// Creates a new instance of message.
        /// <returns>New instance of message of the same type as this.</returns>
        /// </summary>
        protected override IRecordInterface CreateInstance()
        {
            return new BinaryDataType();
        }
        
        /// <summary>
        /// Creates copy of this instance.
        /// <returns>Copy.</returns>
        /// </summary>
        IBinaryDataTypeInfo IBinaryDataTypeInfo.Clone()
        {
            return ((IBinaryDataTypeInfo)(this.CloneImpl()));
        }
        
        /// <summary>
        /// Creates copy of this instance.
        /// <returns>Copy.</returns>
        /// </summary>
        IBinaryDataTypeInterface IBinaryDataTypeInterface.Clone()
        {
            return ((IBinaryDataTypeInterface)(this.CloneImpl()));
        }
        
        /// <summary>
        /// Creates copy of this instance.
        /// <returns>Copy.</returns>
        /// </summary>
        public new BinaryDataType Clone()
        {
            return ((BinaryDataType)(this.CloneImpl()));
        }
        
        /// <summary>
        /// Deep copies content from src instance to this.
        /// <param name="source">Source for copy.</param>
        /// <returns>this.</returns>
        /// </summary>
        protected override IRecordInterface CopyFromImpl(IRecordInfo source)
        {
            base.CopyFromImpl(source);
            if (typeof(IBinaryDataTypeInfo).IsInstanceOfType(source))
            {
                IBinaryDataTypeInfo typedSource = ((IBinaryDataTypeInfo)(source));
                this.MaxSize = typedSource.MaxSize;
                this.CompressionLevel = typedSource.CompressionLevel;
            }
            return this;
        }
        
        /// <summary>
        /// Deep copies content from src instance to this.
        /// <param name="source">Source for copy.</param>
        /// <returns>this.</returns>
        /// </summary>
        IBinaryDataTypeInterface IBinaryDataTypeInterface.CopyFrom(IRecordInfo source)
        {
            return ((IBinaryDataTypeInterface)(this.CopyFromImpl(source)));
        }
        
        /// <summary>
        /// Deep copies content from src instance to this.
        /// <param name="source">Source for copy.</param>
        /// <returns>this.</returns>
        /// </summary>
        public new BinaryDataType CopyFrom(IRecordInfo source)
        {
            return ((BinaryDataType)(this.CopyFromImpl(source)));
        }
        
        /// <summary>
        /// Set null to all fields of this instance.
        /// <returns>this.</returns>
        /// </summary>
        protected override IRecordInterface NullifyImpl()
        {
            base.NullifyImpl();
            this.NullifyMaxSize();
            this.NullifyCompressionLevel();
            return this;
        }
        
        /// <summary>
        /// Set null to all fields of this instance.
        /// <returns>this.</returns>
        /// </summary>
        IBinaryDataTypeInterface IBinaryDataTypeInterface.Nullify()
        {
            return ((IBinaryDataTypeInterface)(this.NullifyImpl()));
        }
        
        /// <summary>
        /// Set null to all fields of this instance.
        /// <returns>this.</returns>
        /// </summary>
        public new BinaryDataType Nullify()
        {
            return ((BinaryDataType)(this.NullifyImpl()));
        }
        
        /// <summary>
        /// Reset all instance field to their default states.
        /// <returns>this.</returns>
        /// </summary>
        protected override IRecordInterface ResetImpl()
        {
            base.ResetImpl();
            this._maxSize = UInt32.MinValue;
            this._compressionLevel = UInt16.MinValue;
            return this;
        }
        
        /// <summary>
        /// Reset all instance field to their default states.
        /// <returns>this.</returns>
        /// </summary>
        IBinaryDataTypeInterface IBinaryDataTypeInterface.Reset()
        {
            return ((IBinaryDataTypeInterface)(this.ResetImpl()));
        }
        
        /// <summary>
        /// Reset all instance field to their default states.
        /// <returns>this.</returns>
        /// </summary>
        public new BinaryDataType Reset()
        {
            return ((BinaryDataType)(this.ResetImpl()));
        }
        #endregion
        
        #region Standard Methods
        /// <summary>
        /// Determines whether the specified object is equal to the current object.
        /// <param name="obj">The object to compare with the current object.</param>
        /// <returns>true if the specified object is equal to the current object; otherwise, false.</returns>
        /// </summary>
        public virtual bool Equals(BinaryDataType obj)
        {
            if ((obj == null))
            {
                return false;
            }
            if ((this.MaxSize != obj.MaxSize))
            {
                return false;
            }
            if ((this.CompressionLevel != obj.CompressionLevel))
            {
                return false;
            }
            return base.Equals(obj);
        }
        
        /// <summary>
        /// Determines whether the specified object is equal to the current object.
        /// <param name="obj">The object to compare with the current object.</param>
        /// <returns>true if the specified object is equal to the current object; otherwise, false.</returns>
        /// </summary>
        public override bool Equals(object obj)
        {
            if ((typeof(BinaryDataType).IsInstanceOfType(obj) == false))
            {
                return false;
            }
            return this.Equals(((BinaryDataType)(obj)));
        }
        
        /// <summary>
        /// Calculates a hash code for the current object.
        /// <returns>A hash code for the current object.</returns>
        /// </summary>
        public override int GetHashCode()
        {
            unchecked
            {
            int hash = ((int)(2166136261u));
            hash = ((hash * 16777619) 
                        + this.MaxSize.GetHashCode());
            hash = ((hash * 16777619) 
                        + this.CompressionLevel.GetHashCode());
            return ((hash * 16777619) 
                        + base.GetHashCode());
            }
        }
        
        /// <summary>
        /// Appends an object state to a given StringBuilder in a form of JSON.
        /// <returns>A StringBuilder that was used to append the object to.</returns>
        /// </summary>
        public override System.Text.StringBuilder ToString(System.Text.StringBuilder builder)
        {
            builder.Append("{ \"$type\":  \"BinaryDataType\"");
            if (this.HasMaxSize())
            {
                builder.Append(", \"MaxSize\": ");
                builder.Append(this.MaxSize);
            }
            if (this.HasCompressionLevel())
            {
                builder.Append(", \"CompressionLevel\": ");
                builder.Append(this.CompressionLevel);
            }
            if (this.HasEncoding())
            {
                builder.Append(", \"Encoding\": \"");
                builder.Append(this.Encoding);
                builder.Append("\"");
            }
            if (this.HasIsNullable())
            {
                builder.Append(", \"IsNullable\": ");
                builder.Append(this.IsNullable);
            }
            builder.Append("}");
            return builder;
        }
        
        /// <summary>
        /// Returns a string that represents the current object.
        /// <returns>A string that represents the current object.</returns>
        /// </summary>
        public override string ToString()
        {
            return this.ToString(new System.Text.StringBuilder()).ToString();
        }
        #endregion
    }
}