//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EPAM.Deltix.Timebase.Messages;
using System;


namespace EPAM.Deltix.Timebase.Messages.Schema
{
    
    
    /// <summary>
    /// Schema definition of binary data type.
    /// </summary>
    public interface IBinaryDataTypeInfo : IDataTypeInfo
    {
        
        #region Properties
        /// <summary>
        /// Maximum field length in bytes.
        /// </summary>
        UInt32 MaxSize
        {
            get;
        }
        
        /// <summary>
        /// Compression level for binary data.
        /// </summary>
        UInt16 CompressionLevel
        {
            get;
        }
        #endregion
        
        #region Methods
        /// <summary>
        /// Flag that indicates whether property MaxSize has an assigned value.
        /// <returns>true if property has an assigned value, false otherwise.</returns>
        /// </summary>
        Boolean HasMaxSize();
        
        /// <summary>
        /// Flag that indicates whether property CompressionLevel has an assigned value.
        /// <returns>true if property has an assigned value, false otherwise.</returns>
        /// </summary>
        Boolean HasCompressionLevel();
        
        /// <summary>
        /// Creates copy of this instance.
        /// <returns>Copy.</returns>
        /// </summary>
        new IBinaryDataTypeInfo Clone();
        #endregion
    }
}
