//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EPAM.Deltix.Timebase.Messages;
using System;
using System.Collections.Generic;


namespace EPAM.Deltix.Timebase.Messages.Schema
{
    
    
    /// <summary>
    /// Schema definition of class data type.
    /// </summary>
    public interface IClassDataTypeInfo : IDataTypeInfo
    {
        
        #region Properties
        /// <summary>
        /// Definitions for nested schema classes.
        /// </summary>
        IReadOnlyList<IClassDescriptorRefInfo> TypeDescriptors
        {
            get;
        }
        #endregion
        
        #region Methods
        /// <summary>
        /// Flag that indicates whether property TypeDescriptors has an assigned value.
        /// <returns>true if property has an assigned value, false otherwise.</returns>
        /// </summary>
        Boolean HasTypeDescriptors();
        
        /// <summary>
        /// Creates copy of this instance.
        /// <returns>Copy.</returns>
        /// </summary>
        new IClassDataTypeInfo Clone();
        #endregion
    }
}
