//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EPAM.Deltix.Timebase.Messages;
using System;
using System.Collections.Generic;


namespace EPAM.Deltix.Timebase.Messages.Schema
{
    
    
    /// <summary>
    /// Schema definition for enumeration class.
    /// </summary>
    public interface IEnumClassDescriptorInterface : IEnumClassDescriptorInfo, IClassDescriptorInterface
    {
        
        #region Properties
        /// <summary>
        /// List of values of enumeration.
        /// </summary>
        new IList<IEnumValueInterface> Values
        {
            get;
            set;
        }
        
        /// <summary>
        /// True, if enumeration represents a bitmask.
        /// </summary>
        new Boolean IsBitmask
        {
            get;
            set;
        }
        #endregion
        
        #region Methods
        /// <summary>
        /// Sets null to Values property.
        /// </summary>
        void NullifyValues();
        
        /// <summary>
        /// Sets null to IsBitmask property.
        /// </summary>
        void NullifyIsBitmask();
        
        /// <summary>
        /// Creates copy of this instance.
        /// <returns>Copy.</returns>
        /// </summary>
        new IEnumClassDescriptorInterface Clone();
        
        /// <summary>
        /// Deep copies content from src instance to this.
        /// <param name="source">Source for copy.</param>
        /// <returns>this.</returns>
        /// </summary>
        new IEnumClassDescriptorInterface CopyFrom(IRecordInfo source);
        
        /// <summary>
        /// Set null to all fields of this instance.
        /// <returns>this.</returns>
        /// </summary>
        new IEnumClassDescriptorInterface Nullify();
        
        /// <summary>
        /// Reset all instance field to their default states.
        /// <returns>this.</returns>
        /// </summary>
        new IEnumClassDescriptorInterface Reset();
        #endregion
    }
}
