//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EPAM.Deltix.Timebase.Messages;
using com.epam.deltix.containers.;
using System;


namespace EPAM.Deltix.Timebase.Messages.Schema
{
    
    
    /// <summary>
    /// Schema definition for a single enumeration value.
    /// </summary>
    public interface IEnumValueInfo : IRecordInfo
    {
        
        #region Properties
        /// <summary>
        /// Enumeration symbol.
        /// </summary>
        String Symbol
        {
            get;
        }
        
        /// <summary>
        /// Enumeration value.
        /// </summary>
        Int16 Value
        {
            get;
        }
        #endregion
        
        #region Methods
        /// <summary>
        /// Flag that indicates whether property Symbol has an assigned value.
        /// <returns>true if property has an assigned value, false otherwise.</returns>
        /// </summary>
        Boolean HasSymbol();
        
        /// <summary>
        /// Flag that indicates whether property Value has an assigned value.
        /// <returns>true if property has an assigned value, false otherwise.</returns>
        /// </summary>
        Boolean HasValue();
        
        /// <summary>
        /// Creates copy of this instance.
        /// <returns>Copy.</returns>
        /// </summary>
        new IEnumValueInfo Clone();
        #endregion
    }
}
