//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EPAM.Deltix.Timebase.Messages;
using com.epam.deltix.containers.;
using System;


namespace EPAM.Deltix.Timebase.Messages.Schema
{
    
    
    /// <summary>
    /// This is a base class for numeric data types.
    /// </summary>
    public interface IIntegralDataTypeInfo : IDataTypeInfo
    {
        
        #region Properties
        /// <summary>
        /// String definition for minimum constraint.
        /// </summary>
        MutableString MinValue
        {
            get;
        }
        
        /// <summary>
        /// String definition for maximum constraint.
        /// </summary>
        MutableString MaxValue
        {
            get;
        }
        #endregion
        
        #region Methods
        /// <summary>
        /// Flag that indicates whether property MinValue has an assigned value.
        /// <returns>true if property has an assigned value, false otherwise.</returns>
        /// </summary>
        Boolean HasMinValue();
        
        /// <summary>
        /// Flag that indicates whether property MaxValue has an assigned value.
        /// <returns>true if property has an assigned value, false otherwise.</returns>
        /// </summary>
        Boolean HasMaxValue();
        
        /// <summary>
        /// Creates copy of this instance.
        /// <returns>Copy.</returns>
        /// </summary>
        new IIntegralDataTypeInfo Clone();
        #endregion
    }
}
