/*
  Copyright 2021 EPAM Systems, Inc

  See the NOTICE file distributed with this work for additional information
  regarding copyright ownership. Licensed under the Apache License,
  Version 2.0 (the "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
  License for the specific language governing permissions and limitations under
  the License.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EPAM.Deltix.Timebase.Messages;
using com.epam.deltix.containers.;
using System;


namespace EPAM.Deltix.Timebase.Messages.Schema
{
    
    
    /// <summary>
    /// This is a base class for schema nodes.
    /// </summary>
    public interface INamedDescriptorInterface : INamedDescriptorInfo, IRecordInterface
    {
        
        #region Properties
        /// <summary>
        /// Node name.
        /// </summary>
        new MutableString Name
        {
            get;
            set;
        }
        
        /// <summary>
        /// Node title.
        /// </summary>
        new MutableString Title
        {
            get;
            set;
        }
        
        /// <summary>
        /// Node description.
        /// </summary>
        new MutableString Description
        {
            get;
            set;
        }
        #endregion
        
        #region Methods
        /// <summary>
        /// Sets null to Name property.
        /// </summary>
        void NullifyName();
        
        /// <summary>
        /// Sets null to Title property.
        /// </summary>
        void NullifyTitle();
        
        /// <summary>
        /// Sets null to Description property.
        /// </summary>
        void NullifyDescription();
        
        /// <summary>
        /// Creates copy of this instance.
        /// <returns>Copy.</returns>
        /// </summary>
        new INamedDescriptorInterface Clone();
        
        /// <summary>
        /// Deep copies content from src instance to this.
        /// <param name="source">Source for copy.</param>
        /// <returns>this.</returns>
        /// </summary>
        new INamedDescriptorInterface CopyFrom(IRecordInfo source);
        
        /// <summary>
        /// Set null to all fields of this instance.
        /// <returns>this.</returns>
        /// </summary>
        new INamedDescriptorInterface Nullify();
        
        /// <summary>
        /// Reset all instance field to their default states.
        /// <returns>this.</returns>
        /// </summary>
        new INamedDescriptorInterface Reset();
        #endregion
    }
}