//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EPAM.Deltix.Timebase.Messages;
using com.epam.deltix.containers.;
using System;


namespace EPAM.Deltix.Timebase.Messages.Schema
{
    
    
    /// <summary>
    /// This is a base class for schema nodes.
    /// </summary>
    public interface INamedDescriptorInfo : IRecordInfo
    {
        
        #region Properties
        /// <summary>
        /// Node name.
        /// </summary>
        MutableString Name
        {
            get;
        }
        
        /// <summary>
        /// Node title.
        /// </summary>
        MutableString Title
        {
            get;
        }
        
        /// <summary>
        /// Node description.
        /// </summary>
        MutableString Description
        {
            get;
        }
        #endregion
        
        #region Methods
        /// <summary>
        /// Flag that indicates whether property Name has an assigned value.
        /// <returns>true if property has an assigned value, false otherwise.</returns>
        /// </summary>
        Boolean HasName();
        
        /// <summary>
        /// Flag that indicates whether property Title has an assigned value.
        /// <returns>true if property has an assigned value, false otherwise.</returns>
        /// </summary>
        Boolean HasTitle();
        
        /// <summary>
        /// Flag that indicates whether property Description has an assigned value.
        /// <returns>true if property has an assigned value, false otherwise.</returns>
        /// </summary>
        Boolean HasDescription();
        
        /// <summary>
        /// Creates copy of this instance.
        /// <returns>Copy.</returns>
        /// </summary>
        new INamedDescriptorInfo Clone();
        #endregion
    }
}
