//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EPAM.Deltix.Timebase.Messages;
using System;
using System.Collections.Generic;


namespace EPAM.Deltix.Timebase.Messages.Schema
{
    
    
    /// <summary>
    /// Schema definition for a class.
    /// </summary>
    public interface IRecordClassDescriptorInfo : IClassDescriptorInfo
    {
        
        #region Properties
        /// <summary>
        /// Defines parent RecordClassDescriptor if exist.
        /// </summary>
        IRecordClassDescriptorInfo Parent
        {
            get;
        }
        
        /// <summary>
        /// Defines if current RecordClassDescriptor is abstract.
        /// </summary>
        Boolean IsAbstract
        {
            get;
        }
        
        /// <summary>
        /// Defines if current RecordClassDescriptor is content class.
        /// </summary>
        Boolean IsContentClass
        {
            get;
        }
        
        /// <summary>
        /// List of fields of a class.
        /// </summary>
        IReadOnlyList<IDataFieldInfo> DataFields
        {
            get;
        }
        #endregion
        
        #region Methods
        /// <summary>
        /// Flag that indicates whether property Parent has an assigned value.
        /// <returns>true if property has an assigned value, false otherwise.</returns>
        /// </summary>
        Boolean HasParent();
        
        /// <summary>
        /// Flag that indicates whether property IsAbstract has an assigned value.
        /// <returns>true if property has an assigned value, false otherwise.</returns>
        /// </summary>
        Boolean HasIsAbstract();
        
        /// <summary>
        /// Flag that indicates whether property IsContentClass has an assigned value.
        /// <returns>true if property has an assigned value, false otherwise.</returns>
        /// </summary>
        Boolean HasIsContentClass();
        
        /// <summary>
        /// Flag that indicates whether property DataFields has an assigned value.
        /// <returns>true if property has an assigned value, false otherwise.</returns>
        /// </summary>
        Boolean HasDataFields();
        
        /// <summary>
        /// Creates copy of this instance.
        /// <returns>Copy.</returns>
        /// </summary>
        new IRecordClassDescriptorInfo Clone();
        #endregion
    }
}
