/*
  Copyright 2021 EPAM Systems, Inc

  See the NOTICE file distributed with this work for additional information
  regarding copyright ownership. Licensed under the Apache License,
  Version 2.0 (the "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
  License for the specific language governing permissions and limitations under
  the License.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EPAM.Deltix.Timebase.Messages;
using com.epam.deltix.containers.;
using System;


namespace EPAM.Deltix.Timebase.Messages.Schema
{
    
    
    /// <summary>
    /// Class which defines a transformation that is applied to a data field.
    /// </summary>
    public interface ISchemaFieldDataTransformationInterface : ISchemaFieldDataTransformationInfo, IRecordInterface
    {
        
        #region Properties
        /// <summary>
        /// Defines the transformation that was applied to the field.
        /// </summary>
        new SchemaFieldDataTransformationType TransformationType
        {
            get;
            set;
        }
        
        /// <summary>
        /// Defines the default value if TransformationType equals SET_DEFAULT.
        /// </summary>
        new MutableString DefaultValue
        {
            get;
            set;
        }
        #endregion
        
        #region Methods
        /// <summary>
        /// Sets null to TransformationType property.
        /// </summary>
        void NullifyTransformationType();
        
        /// <summary>
        /// Sets null to DefaultValue property.
        /// </summary>
        void NullifyDefaultValue();
        
        /// <summary>
        /// Creates copy of this instance.
        /// <returns>Copy.</returns>
        /// </summary>
        new ISchemaFieldDataTransformationInterface Clone();
        
        /// <summary>
        /// Deep copies content from src instance to this.
        /// <param name="source">Source for copy.</param>
        /// <returns>this.</returns>
        /// </summary>
        new ISchemaFieldDataTransformationInterface CopyFrom(IRecordInfo source);
        
        /// <summary>
        /// Set null to all fields of this instance.
        /// <returns>this.</returns>
        /// </summary>
        new ISchemaFieldDataTransformationInterface Nullify();
        
        /// <summary>
        /// Reset all instance field to their default states.
        /// <returns>this.</returns>
        /// </summary>
        new ISchemaFieldDataTransformationInterface Reset();
        #endregion
    }
}