//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EPAM.Deltix.Timebase.Messages;
using System;


namespace EPAM.Deltix.Timebase.Messages.Schema
{
    
    
    /// <summary>
    /// Class which defines a change to schema field.
    /// </summary>
    public interface ISchemaFieldChangeActionInterface : ISchemaFieldChangeActionInfo, IRecordInterface
    {
        
        #region Properties
        /// <summary>
        /// Previous data field state.
        /// </summary>
        new IDataFieldInterface PreviousState
        {
            get;
            set;
        }
        
        /// <summary>
        /// New descriptor state.
        /// </summary>
        new IDataFieldInterface NewState
        {
            get;
            set;
        }
        
        /// <summary>
        /// Bitmask that defines the changes that were applied to the field.
        /// </summary>
        new SchemaFieldChangeType ChangeTypes
        {
            get;
            set;
        }
        
        /// <summary>
        /// Defines the data transformation that was applied to the field.
        /// </summary>
        new ISchemaFieldDataTransformationInterface DataTransformation
        {
            get;
            set;
        }
        #endregion
        
        #region Methods
        /// <summary>
        /// Sets null to PreviousState property.
        /// </summary>
        void NullifyPreviousState();
        
        /// <summary>
        /// Sets null to NewState property.
        /// </summary>
        void NullifyNewState();
        
        /// <summary>
        /// Sets null to ChangeTypes property.
        /// </summary>
        void NullifyChangeTypes();
        
        /// <summary>
        /// Sets null to DataTransformation property.
        /// </summary>
        void NullifyDataTransformation();
        
        /// <summary>
        /// Creates copy of this instance.
        /// <returns>Copy.</returns>
        /// </summary>
        new ISchemaFieldChangeActionInterface Clone();
        
        /// <summary>
        /// Deep copies content from src instance to this.
        /// <param name="source">Source for copy.</param>
        /// <returns>this.</returns>
        /// </summary>
        new ISchemaFieldChangeActionInterface CopyFrom(IRecordInfo source);
        
        /// <summary>
        /// Set null to all fields of this instance.
        /// <returns>this.</returns>
        /// </summary>
        new ISchemaFieldChangeActionInterface Nullify();
        
        /// <summary>
        /// Reset all instance field to their default states.
        /// <returns>this.</returns>
        /// </summary>
        new ISchemaFieldChangeActionInterface Reset();
        #endregion
    }
}
