//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EPAM.Deltix.Timebase.Messages;
using System;


namespace EPAM.Deltix.Timebase.Messages.Schema
{
    
    
    /// <summary>
    /// Schema definition of varchar data type.
    /// </summary>
    public interface IVarcharDataTypeInterface : IVarcharDataTypeInfo, IDataTypeInterface
    {
        
        #region Properties
        /// <summary>
        /// True, if field allows line breaks.
        /// </summary>
        new Boolean IsMultiline
        {
            get;
            set;
        }
        
        /// <summary>
        /// Encoding type.
        /// </summary>
        new UInt32 EncodingType
        {
            get;
            set;
        }
        
        /// <summary>
        /// Length.
        /// </summary>
        new UInt32 Length
        {
            get;
            set;
        }
        #endregion
        
        #region Methods
        /// <summary>
        /// Sets null to IsMultiline property.
        /// </summary>
        void NullifyIsMultiline();
        
        /// <summary>
        /// Sets null to EncodingType property.
        /// </summary>
        void NullifyEncodingType();
        
        /// <summary>
        /// Sets null to Length property.
        /// </summary>
        void NullifyLength();
        
        /// <summary>
        /// Creates copy of this instance.
        /// <returns>Copy.</returns>
        /// </summary>
        new IVarcharDataTypeInterface Clone();
        
        /// <summary>
        /// Deep copies content from src instance to this.
        /// <param name="source">Source for copy.</param>
        /// <returns>this.</returns>
        /// </summary>
        new IVarcharDataTypeInterface CopyFrom(IRecordInfo source);
        
        /// <summary>
        /// Set null to all fields of this instance.
        /// <returns>this.</returns>
        /// </summary>
        new IVarcharDataTypeInterface Nullify();
        
        /// <summary>
        /// Reset all instance field to their default states.
        /// <returns>this.</returns>
        /// </summary>
        new IVarcharDataTypeInterface Reset();
        #endregion
    }
}
