//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EPAM.Deltix.Timebase.Messages;
using System;


namespace EPAM.Deltix.Timebase.Messages.Schema
{
    
    
    /// <summary>
    /// Type of transformation applied to the descriptor.
    /// </summary>
    [SchemaElement(Name="com.epam.deltix.timebase.messages.schema.SchemaDescriptorTransformationType", Title="SchemaDescriptorTransformationType", Description=null)]
    public enum SchemaDescriptorTransformationType
    {
        
        /// <summary>
        /// Drop record operation.
        /// </summary>
        [SchemaElement(Name="DROP_RECORD", Title=null, Description=null)]
        DropRecord = 0,
    }
}
