//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EPAM.Deltix.Timebase.Messages;
using System;


namespace EPAM.Deltix.Timebase.Messages.Schema
{
    
    
    /// <summary>
    /// Type of descriptor change.
    /// </summary>
    [Bitmask()]
    [SchemaElement(Name="com.epam.deltix.timebase.messages.schema.SchemaDescriptorChangeType", Title="SchemaDescriptorChangeType", Description=null)]
    public enum SchemaDescriptorChangeType
    {
        
        /// <summary>
        /// Add operation.
        /// </summary>
        [SchemaElement(Name="ADD", Title=null, Description=null)]
        Add = 1,
        
        /// <summary>
        /// Delete operation.
        /// </summary>
        [SchemaElement(Name="DELETE", Title=null, Description=null)]
        Delete = 2,
        
        /// <summary>
        /// Rename operation.
        /// </summary>
        [SchemaElement(Name="RENAME", Title=null, Description=null)]
        Rename = 4,
        
        /// <summary>
        /// Fields change operation.
        /// </summary>
        [SchemaElement(Name="FIELDS_CHANGE", Title=null, Description=null)]
        FieldsChange = 8,
        
        /// <summary>
        /// Content type change operation.
        /// </summary>
        [SchemaElement(Name="CONTENT_TYPE_CHANGE", Title=null, Description=null)]
        ContentTypeChange = 16,
    }
}
