//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EPAM.Deltix.Timebase.Messages;
using System;


namespace EPAM.Deltix.Timebase.Messages.Schema
{
    
    
    /// <summary>
    /// Type of transformation applied to data field.
    /// </summary>
    [SchemaElement(Name="com.epam.deltix.timebase.messages.schema.SchemaFieldDataTransformationType", Title="SchemaFieldDataTransformationType", Description=null)]
    public enum SchemaFieldDataTransformationType
    {
        
        /// <summary>
        /// Convert data operation.
        /// </summary>
        [SchemaElement(Name="CONVERT_DATA", Title=null, Description=null)]
        ConvertData = 0,
        
        /// <summary>
        /// Apply default value operation.
        /// </summary>
        [SchemaElement(Name="SET_DEFAULT", Title=null, Description=null)]
        SetDefault = 1,
        
        /// <summary>
        /// Drop record operation.
        /// </summary>
        [SchemaElement(Name="DROP_RECORD", Title=null, Description=null)]
        DropRecord = 2,
    }
}
