/*
  Copyright 2021 EPAM Systems, Inc

  See the NOTICE file distributed with this work for additional information
  regarding copyright ownership. Licensed under the Apache License,
  Version 2.0 (the "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
  License for the specific language governing permissions and limitations under
  the License.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EPAM.Deltix.Timebase.Messages;
using System;


namespace EPAM.Deltix.Timebase.Messages.Schema
{
    
    
    /// <summary>
    /// Type of field change.
    /// </summary>
    [Bitmask()]
    [SchemaElement(Name="com.epam.deltix.timebase.messages.schema.SchemaFieldChangeType", Title="SchemaFieldChangeType", Description=null)]
    public enum SchemaFieldChangeType
    {
        
        /// <summary>
        /// Add field or enumeration value operation.
        /// </summary>
        [SchemaElement(Name="ADD", Title=null, Description=null)]
        Add = 1,
        
        /// <summary>
        /// Delete field or enumeration value operation.
        /// </summary>
        [SchemaElement(Name="DELETE", Title=null, Description=null)]
        Delete = 2,
        
        /// <summary>
        /// Rename field or enumeration value operation.
        /// </summary>
        [SchemaElement(Name="RENAME", Title=null, Description=null)]
        Rename = 4,
        
        /// <summary>
        /// Change field title operation.
        /// </summary>
        [SchemaElement(Name="TITLE_CHANGE", Title=null, Description=null)]
        TitleChange = 8,
        
        /// <summary>
        /// Change field description operation.
        /// </summary>
        [SchemaElement(Name="DESCRIPTION_CHANGE", Title=null, Description=null)]
        DescriptionChange = 16,
        
        /// <summary>
        /// Change field data type operation.
        /// </summary>
        [SchemaElement(Name="DATA_TYPE_CHANGE", Title=null, Description=null)]
        DataTypeChange = 32,
        
        /// <summary>
        /// Change field ordinal operation.
        /// </summary>
        [SchemaElement(Name="ORDINAL_CHANGE", Title=null, Description=null)]
        OrdinalChange = 64,
        
        /// <summary>
        /// Change field modifier (static and non-static) operation.
        /// </summary>
        [SchemaElement(Name="MODIFIER_CHANGE", Title=null, Description=null)]
        ModifierChange = 128,
        
        /// <summary>
        /// Change field static value operation.
        /// </summary>
        [SchemaElement(Name="STATIC_VALUE_CHANGE", Title=null, Description=null)]
        StaticValueChange = 256,
        
        /// <summary>
        /// Change fileld primary key attribute operation.
        /// </summary>
        [SchemaElement(Name="PRIMARY_KEY_CHANGE", Title=null, Description=null)]
        PrimaryKeyChange = 512,
        
        /// <summary>
        /// Change field relation attribute operation.
        /// </summary>
        [SchemaElement(Name="RELATION_CHANGE", Title=null, Description=null)]
        RelationChange = 1024,
    }
}