/*
  Copyright 2021 EPAM Systems, Inc

  See the NOTICE file distributed with this work for additional information
  regarding copyright ownership. Licensed under the Apache License,
  Version 2.0 (the "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
  License for the specific language governing permissions and limitations under
  the License.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EPAM.Deltix.Timebase.Messages;
using com.epam.deltix.containers.;
using System;


namespace EPAM.Deltix.Timebase.Messages.Schema
{
    
    
    /// <summary>
    /// Schema definition for static data field.
    /// </summary>
    [SchemaElement(Name="com.epam.deltix.timebase.messages.schema.StaticDataField", Title="StaticDataField", Description=null)]
    public class StaticDataField : DataField, IStaticDataFieldInterface
    {
        
        public new static string ClassName = "com.epam.deltix.timebase.messages.schema.StaticDataField";
        
        private MutableString _staticValue = null;
        
        /// <summary>
        /// Creates an instance of StaticDataField object.
        /// </summary>
        public StaticDataField()
        {
        }
        
        #region Properties
        /// <summary>
        /// Value constant for a field.
        /// </summary>
        [SchemaElement(Name=null, Title=null, Description=null)]
        [SchemaType(Encoding=null, IsNullable=true, DataType=SchemaDataType.Default, Minimum=null, Maximum=null, NestedTypes=new Type[0])]
        public virtual MutableString StaticValue
        {
            get
            {
                return this._staticValue;
            }
            set
            {
                this._staticValue = value;
            }
        }
        #endregion
        
        #region Property Helpers
        /// <summary>
        /// Flag that indicates whether property StaticValue has an assigned value.
        /// <returns>true if property has an assigned value, false otherwise.</returns>
        /// </summary>
        public bool HasStaticValue()
        {
            return (this._staticValue != null);
        }
        
        /// <summary>
        /// Sets null to StaticValue property.
        /// </summary>
        public void NullifyStaticValue()
        {
            this._staticValue = null;
        }
        #endregion
        
        #region Message Methods
        /// <summary>
        /// Creates a new instance of message.
        /// <returns>New instance of message of the same type as this.</returns>
        /// </summary>
        protected override IRecordInterface CreateInstance()
        {
            return new StaticDataField();
        }
        
        /// <summary>
        /// Creates copy of this instance.
        /// <returns>Copy.</returns>
        /// </summary>
        IStaticDataFieldInfo IStaticDataFieldInfo.Clone()
        {
            return ((IStaticDataFieldInfo)(this.CloneImpl()));
        }
        
        /// <summary>
        /// Creates copy of this instance.
        /// <returns>Copy.</returns>
        /// </summary>
        IStaticDataFieldInterface IStaticDataFieldInterface.Clone()
        {
            return ((IStaticDataFieldInterface)(this.CloneImpl()));
        }
        
        /// <summary>
        /// Creates copy of this instance.
        /// <returns>Copy.</returns>
        /// </summary>
        public new StaticDataField Clone()
        {
            return ((StaticDataField)(this.CloneImpl()));
        }
        
        /// <summary>
        /// Deep copies content from src instance to this.
        /// <param name="source">Source for copy.</param>
        /// <returns>this.</returns>
        /// </summary>
        protected override IRecordInterface CopyFromImpl(IRecordInfo source)
        {
            base.CopyFromImpl(source);
            if (typeof(IStaticDataFieldInfo).IsInstanceOfType(source))
            {
                IStaticDataFieldInfo typedSource = ((IStaticDataFieldInfo)(source));
                if ((typedSource.StaticValue != null))
                {
                    if ((this.StaticValue == null))
                    {
                        this.StaticValue = new com.epam.deltix.containers.MutableString(typedSource.StaticValue);
                    }
                    else
                    {
                        this.StaticValue.Assign(typedSource.StaticValue);
                    }
                }
                else
                {
                    this.StaticValue = null;
                }
            }
            return this;
        }
        
        /// <summary>
        /// Deep copies content from src instance to this.
        /// <param name="source">Source for copy.</param>
        /// <returns>this.</returns>
        /// </summary>
        IStaticDataFieldInterface IStaticDataFieldInterface.CopyFrom(IRecordInfo source)
        {
            return ((IStaticDataFieldInterface)(this.CopyFromImpl(source)));
        }
        
        /// <summary>
        /// Deep copies content from src instance to this.
        /// <param name="source">Source for copy.</param>
        /// <returns>this.</returns>
        /// </summary>
        public new StaticDataField CopyFrom(IRecordInfo source)
        {
            return ((StaticDataField)(this.CopyFromImpl(source)));
        }
        
        /// <summary>
        /// Set null to all fields of this instance.
        /// <returns>this.</returns>
        /// </summary>
        protected override IRecordInterface NullifyImpl()
        {
            base.NullifyImpl();
            this.NullifyStaticValue();
            return this;
        }
        
        /// <summary>
        /// Set null to all fields of this instance.
        /// <returns>this.</returns>
        /// </summary>
        IStaticDataFieldInterface IStaticDataFieldInterface.Nullify()
        {
            return ((IStaticDataFieldInterface)(this.NullifyImpl()));
        }
        
        /// <summary>
        /// Set null to all fields of this instance.
        /// <returns>this.</returns>
        /// </summary>
        public new StaticDataField Nullify()
        {
            return ((StaticDataField)(this.NullifyImpl()));
        }
        
        /// <summary>
        /// Reset all instance field to their default states.
        /// <returns>this.</returns>
        /// </summary>
        protected override IRecordInterface ResetImpl()
        {
            base.ResetImpl();
            this._staticValue = null;
            return this;
        }
        
        /// <summary>
        /// Reset all instance field to their default states.
        /// <returns>this.</returns>
        /// </summary>
        IStaticDataFieldInterface IStaticDataFieldInterface.Reset()
        {
            return ((IStaticDataFieldInterface)(this.ResetImpl()));
        }
        
        /// <summary>
        /// Reset all instance field to their default states.
        /// <returns>this.</returns>
        /// </summary>
        public new StaticDataField Reset()
        {
            return ((StaticDataField)(this.ResetImpl()));
        }
        #endregion
        
        #region Standard Methods
        /// <summary>
        /// Determines whether the specified object is equal to the current object.
        /// <param name="obj">The object to compare with the current object.</param>
        /// <returns>true if the specified object is equal to the current object; otherwise, false.</returns>
        /// </summary>
        public virtual bool Equals(StaticDataField obj)
        {
            if ((obj == null))
            {
                return false;
            }
            if (((this.StaticValue != null) 
                        && (obj.StaticValue != null)))
            {
                if ((this.StaticValue.Equals(obj.StaticValue) != true))
                {
                    return false;
                }
            }
            else
            {
                if ((this.StaticValue != obj.StaticValue))
                {
                    return false;
                }
            }
            return base.Equals(obj);
        }
        
        /// <summary>
        /// Determines whether the specified object is equal to the current object.
        /// <param name="obj">The object to compare with the current object.</param>
        /// <returns>true if the specified object is equal to the current object; otherwise, false.</returns>
        /// </summary>
        public override bool Equals(object obj)
        {
            if ((typeof(StaticDataField).IsInstanceOfType(obj) == false))
            {
                return false;
            }
            return this.Equals(((StaticDataField)(obj)));
        }
        
        /// <summary>
        /// Calculates a hash code for the current object.
        /// <returns>A hash code for the current object.</returns>
        /// </summary>
        public override int GetHashCode()
        {
            unchecked
            {
            int hash = ((int)(2166136261u));
            if ((this.StaticValue == null))
            {
                hash = ((hash * 16777619) 
                            + 0);
            }
            else
            {
                hash = ((hash * 16777619) 
                            + this.StaticValue.GetHashCode());
            }
            return ((hash * 16777619) 
                        + base.GetHashCode());
            }
        }
        
        /// <summary>
        /// Appends an object state to a given StringBuilder in a form of JSON.
        /// <returns>A StringBuilder that was used to append the object to.</returns>
        /// </summary>
        public override System.Text.StringBuilder ToString(System.Text.StringBuilder builder)
        {
            builder.Append("{ \"$type\":  \"StaticDataField\"");
            if (this.HasStaticValue())
            {
                builder.Append(", \"StaticValue\": \"");
                builder.Append(this.StaticValue);
                builder.Append("\"");
            }
            if (this.HasDataType())
            {
                builder.Append(", \"DataType\": {");
                this.DataType.ToString(builder);
                builder.Append("}");
            }
            if (this.HasName())
            {
                builder.Append(", \"Name\": \"");
                builder.Append(this.Name);
                builder.Append("\"");
            }
            if (this.HasTitle())
            {
                builder.Append(", \"Title\": \"");
                builder.Append(this.Title);
                builder.Append("\"");
            }
            if (this.HasDescription())
            {
                builder.Append(", \"Description\": \"");
                builder.Append(this.Description);
                builder.Append("\"");
            }
            builder.Append("}");
            return builder;
        }
        
        /// <summary>
        /// Returns a string that represents the current object.
        /// <returns>A string that represents the current object.</returns>
        /// </summary>
        public override string ToString()
        {
            return this.ToString(new System.Text.StringBuilder()).ToString();
        }
        #endregion
    }
}