plugins {
    id 'me.champeau.gradle.jmh' version '0.4.5' apply false
}

description = 'QuantServer commons-lang set of utilities'

dependencies {
    api "com.epam.deltix:dfp"
    api 'com.epam.deltix:gflog-api'
    api "deltix:hd-date-time"

    // For JMH-based tests
    testImplementation 'org.openjdk.jmh:jmh-core'
    testImplementation 'org.openjdk.jmh:jmh-generator-annprocess'
}