description = 'QuantServer commons-lang set of utilities'

dependencies {
    compile group: 'deltix', name: 'deltix-dfp', version: dfpVersion
    compile group: 'deltix', name: 'hd-date-time', version: hdTimeVersion
    compile 'deltix:deltix-gflog-api'

    testCompile 'org.openjdk.jmh:jmh-core'
    testCompile 'org.openjdk.jmh:jmh-generator-annprocess'

}
