/*
  Copyright 2021 EPAM Systems, Inc

  See the NOTICE file distributed with this work for additional information
  regarding copyright ownership. Licensed under the Apache License,
  Version 2.0 (the "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
  License for the specific language governing permissions and limitations under
  the License.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EPAM.Deltix.Timebase.Messages;
using System;


namespace EPAM.Deltix.Timebase.Messages.Service
{
    
    
    /// <summary>
    /// Message class, which describes data loss for 'lossy' Transient streams. See see "BufferOptions.Lossless".
    /// Such message can be received from see "ITickCursor", when message loss is occurred.
    /// TickStream should have see "DataLossMessage" Class Descriptor defined in stream schema. See
    /// see "Descriptor" .
    /// </summary>
    [OldElementName(Value="deltix.qsrv.hf.pub.DataLossMessage")]
    [SchemaElement(Name="com.epam.deltix.timebase.messages.service.DataLossMessage", Title="Data Loss Message", Description=null)]
    [SchemaGuid(Value=DataLossMessage.DescriptorGuid)]
    public class DataLossMessage : SystemMessage
    {
        
        public const String DescriptorGuid = "SYS:DataLossMessage:2";
        
        private Int64 _bytes = TypeConstants.Int64Null;
        
        private DateTime _fromTime = TypeConstants.TimestampNull;
        
        /// <summary>
        /// Creates an instance of DataLossMessage object.
        /// </summary>
        public DataLossMessage()
        {
        }
        
        #region Properties
        /// <summary>
        /// Number of the lost bytes.
        /// </summary>
        [SchemaElement(Name="bytes", Title="Bytes", Description=null)]
        public virtual Int64 Bytes
        {
            get
            {
                return this._bytes;
            }
            set
            {
                this._bytes = value;
            }
        }
        
        /// <summary>
        /// The last reported message time before byte loss occurs. Precision - milliseconds.
        /// </summary>
        [SchemaElement(Name="fromTime", Title="From Time", Description=null)]
        public virtual DateTime FromTime
        {
            get
            {
                return this._fromTime;
            }
            set
            {
                this._fromTime = value;
            }
        }
        #endregion
        
        #region Property Helpers
        /// <summary>
        /// Flag that indicates whether property Bytes has an assigned value.
        /// <returns>true if property has an assigned value, false otherwise.</returns>
        /// </summary>
        public bool HasBytes()
        {
            return (this._bytes != TypeConstants.Int64Null);
        }
        
        /// <summary>
        /// Sets null to Bytes property.
        /// </summary>
        public void NullifyBytes()
        {
            this._bytes = TypeConstants.Int64Null;
        }
        
        /// <summary>
        /// Flag that indicates whether property FromTime has an assigned value.
        /// <returns>true if property has an assigned value, false otherwise.</returns>
        /// </summary>
        public bool HasFromTime()
        {
            return (this._fromTime != TypeConstants.TimestampNull);
        }
        
        /// <summary>
        /// Sets null to FromTime property.
        /// </summary>
        public void NullifyFromTime()
        {
            this._fromTime = TypeConstants.TimestampNull;
        }
        #endregion
        
        #region Standard Methods
        /// <summary>
        /// Determines whether the specified object is equal to the current object.
        /// <param name="obj">The object to compare with the current object.</param>
        /// <returns>true if the specified object is equal to the current object; otherwise, false.</returns>
        /// </summary>
        public virtual bool Equals(DataLossMessage obj)
        {
            if ((obj == null))
            {
                return false;
            }
            if ((this.Bytes != obj.Bytes))
            {
                return false;
            }
            if ((this.FromTime != obj.FromTime))
            {
                return false;
            }
            return base.Equals(obj);
        }
        
        /// <summary>
        /// Determines whether the specified object is equal to the current object.
        /// <param name="obj">The object to compare with the current object.</param>
        /// <returns>true if the specified object is equal to the current object; otherwise, false.</returns>
        /// </summary>
        public override bool Equals(object obj)
        {
            if ((typeof(DataLossMessage).IsInstanceOfType(obj) == false))
            {
                return false;
            }
            return this.Equals(((DataLossMessage)(obj)));
        }
        
        /// <summary>
        /// Calculates a hash code for the current object.
        /// <returns>A hash code for the current object.</returns>
        /// </summary>
        public override int GetHashCode()
        {
            unchecked
            {
            int hash = ((int)(2166136261u));
            hash = ((hash * 16777619) 
                        + this.Bytes.GetHashCode());
            hash = ((hash * 16777619) 
                        + this.FromTime.GetHashCode());
            return ((hash * 16777619) 
                        + base.GetHashCode());
            }
        }
        
        /// <summary>
        /// Appends an object state to a given StringBuilder in a form of JSON.
        /// <returns>A StringBuilder that was used to append the object to.</returns>
        /// </summary>
        public override System.Text.StringBuilder ToString(System.Text.StringBuilder builder)
        {
            builder.Append("{ \"$type\":  \"DataLossMessage\"");
            if (this.HasBytes())
            {
                builder.Append(", \"Bytes\": ");
                builder.Append(this.Bytes);
            }
            if (this.HasFromTime())
            {
                builder.Append(", \"FromTime\": \"");
                builder.Append(this.FromTime);
                builder.Append("\"");
            }
            if (this.HasTimeStampMs())
            {
                builder.Append(", \"TimeStampMs\": \"");
                builder.Append(this.TimeStampMs);
                builder.Append("\"");
            }
            if (this.HasNanoTime())
            {
                builder.Append(", \"NanoTime\": \"");
                builder.Append(this.NanoTime);
                builder.Append("\"");
            }
            if (this.HasSymbol())
            {
                builder.Append(", \"Symbol\": \"");
                builder.Append(this.Symbol);
                builder.Append("\"");
            }
            builder.Append("}");
            return builder;
        }
        
        /// <summary>
        /// Returns a string that represents the current object.
        /// <returns>A string that represents the current object.</returns>
        /// </summary>
        public override string ToString()
        {
            return this.ToString(new System.Text.StringBuilder()).ToString();
        }
        #endregion
    }
}