//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EPAM.Deltix.Timebase.Messages;
using System;


namespace EPAM.Deltix.Timebase.Messages.Service
{
    
    
    public enum ErrorLevel
    {
        
        [SchemaElement(Name="DEBUG", Title=null, Description=null)]
        Debug = 0,
        
        /// <summary>
        /// Maps to QuantOffice EventSeverity.Information
        /// </summary>
        [SchemaElement(Name="INFO", Title=null, Description=null)]
        Info = 1,
        
        /// <summary>
        /// Maps to QuantOffice EventSeverity.Warning
        /// </summary>
        [SchemaElement(Name="ALERT", Title=null, Description=null)]
        Alert = 2,
        
        /// <summary>
        /// Application/User code error
        /// Maps to QuantOffice EventSeverity.Error, will be visible as Trading Console alert
        /// </summary>
        [SchemaElement(Name="USER_ERROR", Title=null, Description=null)]
        UserError = 3,
        
        /// <summary>
        /// System error (Error in UHF/QuantOffice runtime)
        /// </summary>
        [SchemaElement(Name="SYSTEM_ERROR", Title=null, Description=null)]
        SystemError = 4,
        
        [SchemaElement(Name="HEARTBEAT", Title=null, Description=null)]
        Heartbeat = 5,
    }
}
