//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EPAM.Deltix.Timebase.Messages;
using System;


namespace EPAM.Deltix.Timebase.Messages.Service
{
    
    
    [OldElementName(Value="deltix.qsrv.hf.pub.EventMessage$EventType")]
    [SchemaElement(Name="com.epam.deltix.timebase.messages.service.EventMessageType", Title="Event Type", Description=null)]
    public enum EventMessageType
    {
        
        [SchemaElement(Name="STREAM_DELETED", Title=null, Description=null)]
        StreamDeleted = 0,
        
        [SchemaElement(Name="STREAM_CREATED", Title=null, Description=null)]
        StreamCreated = 1,
        
        [SchemaElement(Name="READ_LOCK_ACQUIRED", Title=null, Description=null)]
        ReadLockAcquired = 2,
        
        [SchemaElement(Name="READ_LOCK_RELEASED", Title=null, Description=null)]
        ReadLockReleased = 3,
        
        [SchemaElement(Name="WRITE_LOCK_ACQUIRED", Title=null, Description=null)]
        WriteLockAcquired = 4,
        
        [SchemaElement(Name="WRITE_LOCK_RELEASED", Title=null, Description=null)]
        WriteLockReleased = 5,
    }
}
